onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
publicHoistPattern:
  - jiti
  - lodash-es
  - ofetch
  - '@types/lodash-es'
